### ISSUE TITLE
User selectable port possible?

### ISSUE THREAD

**Issue by no0ID** [kkebo/DNSecure#39] opened 2021-02-22 07:38 UTC
There are DoT servers offering different ports, maybe useful to be implemented into DNSecure, if possible.
Here an example:

IPv4 address: 146.255.56.98
IPv6 address: 2a02:1b8:10:234::2
TCP port: 443 or 853
Name for TLS verification: dot1.applied-privacy.net
TLSA record: available
TCP Fast Open support: no

**Comment by kkk669** [comment] 2021-02-23 07:53
Duplicate of #11

**Closed by kkk669** 2021-02-23 07:53 UTC
Labels: duplicate
